version: 2

project_name: wtx

before:
  hooks:
    - go mod tidy

builds:
  - id: wtx
    main: .
    binary: wtx
    ldflags:
      - -s -w -X main.version={{ .FullCommit }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: wtx
    builds:
      - wtx
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  name_template: "latest"
  replace_existing_artifacts: true
